# This is a workflow to perform basic verification for KoLmafia ASH scripts

name: CI

on: [push, pull_request]

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        script: [ 'AcquireBuff', 'CreationCost', 'FamiliarDrops', 'PvPHistory', 'RelaySnapshot' ]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 16

    - name: Determine KoLmafia version
      id: mafia
      run: |
        set -o pipefail
        export MAFIA_BUILD=$(curl --fail --silent --globoff 'https://ci.kolmafia.us/job/Kolmafia/api/json?tree=lastCompletedBuild[changeSet[items[revision]]]' | jq '.lastCompletedBuild.changeSet.items[0].revision')
        if [[ -z "$MAFIA_BUILD" ]]; then
          echo "Could not determine mafia version of Jenkins last completed build!"
          exit 1
        fi
        export JENKINS_URL="https://ci.kolmafia.us/job/Kolmafia/lastCompletedBuild/artifact/dist/KoLmafia-${MAFIA_BUILD}.jar"
        echo "::set-output name=jenkins::$JENKINS_URL"
        echo "Jenkins URL = ${JENKINS_URL}"
        echo "::set-output name=build::$MAFIA_BUILD"
        echo "Jenkins Mafia Build = ${MAFIA_BUILD}"

    - name: Cache KoLmafia
      id: cache
      uses: actions/cache@v2
      with:
        path: .github/kolmafia.jar
        key: kolmafia-${{steps.mafia.outputs.build}}

    - name: Download KoLmafia
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        curl "${{steps.mafia.outputs.jenkins}}" --output .github/kolmafia.jar

    - name: Install and verify ${{ matrix.Script }}
      run: |
        echo "============================================="
        echo "== Verifying ${{ matrix.Script }}"
        echo "============================================="
        cd "${{ matrix.Script }}"

        chmod +x ./.github/verify.sh
        ../.github/verify.sh

        if [ $? -ne 0 ]; then
          echo "Error verifying ${{ matrix.Script }}"
          exit 1
        fi

        echo "Verified ${{ matrix.Script }}"
        exit 0
