# This is a workflow to perform basic verification for KoLmafia ASH scripts

name: CI

on: [push, pull_request]

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        script: [ 'AcquireBuff', 'CreationCost', 'FamiliarDrops', 'PvPHistory', 'RelaySkills', 'RelaySnapshot' ]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 16

    - name: Determine KoLmafia version
      id: mafia
      run: |
        set -o pipefail
        export GITHUB_RELEASE=$(curl --fail --silent --globoff 'https://api.github.com/repos/kolmafia/kolmafia/releases/latest')
        if [[ -z "$GITHUB_RELEASE" ]]; then
          echo "Could not get KoLmafia latst release from GitHub!"
          exit 1
        fi
        export GITHUB_BUILD=echo $GITHUB_RELEASE | jq '.assets[0].name')
        export GITHUB_URL=export BUILD=echo $GITHUB_RELEASE | jq '.assets[0].browser_download_url')
        echo "::set-output name=github::$GITHUB_URL"
        echo "GitHub URL = ${GITHUB_URL}"
        echo "::set-output name=build::$GITHUB_BUILD"
        echo "GitHub Mafia Build = ${GITHUB_BUILD}"

    - name: Cache KoLmafia
      id: cache
      uses: actions/cache@v2
      with:
        path: .github/kolmafia.jar
        key: kolmafia-${{steps.mafia.outputs.build}}

    - name: Download KoLmafia
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        curl "${{steps.mafia.outputs.github}}" --output .github/kolmafia.jar

    - name: Install and verify ${{ matrix.Script }}
      env:
        SCRIPT: ${{ matrix.Script }}
      run: |
        echo "============================================="
        echo "== Verifying $SCRIPT"
        echo "============================================="
        cd "$SCRIPT"

        chmod +x ../.github/verify.sh
        ../.github/verify.sh

        if [ $? -ne 0 ]; then
          echo "Error verifying $SCRIPT"
          exit 1
        fi

        echo "Verified $SCRIPT"
        exit 0
